# Generated by Django 3.0 on 2026-02-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='detected_image',
            field=models.CharField(default='', max_length=700),
        ),
    ]
